### ISSUE TITLE
Not workin in translation challenge

### ISSUE THREAD

**Issue by Nudin** [blmage/duolingo-tts-controls#104]
In the course Spanish for German speaker there is one type of questions where the controls are missing:
![Bildschirmfoto](https://user-images.githubusercontent.com/509205/110257520-9cf82300-7f9e-11eb-8658-de0c16e1e239.png)

According to your explanation in [this](https://github.com/blmage/duolingo-tts-controls/issues/93#issuecomment-726754677) issue, I extracted the challenge type to be `challenge challenge-translate`.

Thanks for the addon, finally a way to change the volume for duo!

**Comment by blmage** [comment]
Actually, the extension only applies to listening challenges.

I did consider at the time developing another small extension focused on providing a global volume control, then came across a discussion where someone suggested using the [Volume Master extension](https://chrome.google.com/webstore/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke), which seemed to fit perfectly, and even allowed to increase the volume over 100% (should have checked the browser support..).

Anyway, someone has since developed a [userscript](https://forum.duolingo.com/comment/41474453) that should also do the trick. It doesn't seem to handle the case where the [howler.js library](https://howlerjs.com/) is not used, but I'm not sure if that's still relevant (the `web_remove_howler` A/B test still exists though).

I'll keep this issue opened, because in hindsight there's probably still room for a new browser extension, especially given that it should also be possible to provide a control for each type of sound.

**Comment by blmage** [comment]
This type of challenge is now (at last!) supported in version `2.0.0` .

Also, in case you might be interested, I'm currently working on another extension to provide fine-grained volume controls (by sound type and by context), which should be available soon.
